### ISSUE TITLE
Consider including version information with shared results

### ISSUE THREAD

**Issue by ckthorp** [tenseg/subcaucus-calculator#43]
If there ever were a buggy version, it would be nice to have a version or Git hash (or something similar) on both the screen itself (in case people print/save PDF from the browser) and in the snapshot data (the URL encode).  That way we would know what version generated the results if there were ever a formal challenge filed that related to a hypothetical buggy version.

**Comment by efc** [comment]
Chris, we do have a version number on the data internally (in the local storage on the site), but we do not export that to plain text, CSV, JSON, or the link that we share. My reasoning there is that since "real people" see those formats, I don't want to encumber them with internal baggage. We could reconsider that, especially for JSON and the link, which are both kind of techie anyway.

The JSON is a special case, because it is what we use internally to communicate data. We keep a version number in the root `subcalc3` data element (currently at version 2), but I notice that we do not propagate that data version to the "snapshots" we save in local storage or pass around between users. I think including the data version there would make sense in the future. For now we will leave it without a version, but as soon as we make any change to the format we will add a version element and keep it in sync with the data version used in `subcalc3`.

As far as the email, text, and CSV exports, I don't think a data version number is of any real use, since they are never consumed by the system directly. But in these cases your idea of sharing the SubCalc app version number might help users understand where the data came from. We will add that app version number to those exports.

**Comment by efc** [comment]
Most of this will be available with version 3.1.1 coming soon.
